import puppeteer from "puppeteer";

export async function generateReportPDF(
  report: any
) {

  const browser =
    await puppeteer.launch({

      headless: true,

      args: [

        "--no-sandbox",

        "--disable-setuid-sandbox",

      ],

    });

  const page =
    await browser.newPage();

  const html = `
<!DOCTYPE html>

<html>

<head>

<style>

body{

font-family:Arial,sans-serif;

padding:50px;

color:#222;

}

.header{

background:#0f172a;

color:white;

padding:30px;

border-radius:12px;

}

.section{

margin-top:30px;

padding:20px;

border:1px solid #ddd;

border-radius:10px;

}

h2{

margin:0;

}

table{

width:100%;

border-collapse:collapse;

margin-top:15px;

}

td{

padding:10px;

border:1px solid #ddd;

}

.footer{

margin-top:60px;

font-size:12px;

text-align:center;

color:#777;

}

</style>

</head>

<body>

<div class="header">

<h1>SafeSocial</h1>

<h2>Official Investigation Report</h2>

</div>

<div class="section">

<h3>Incident Summary</h3>

<p>

${report.incident_summary}

</p>

</div>

<div class="section">

<h3>AI Analysis</h3>

<p>

${report.ai_summary}

</p>

</div>

<div class="section">

<h3>Investigation Findings</h3>

<p>

${report.findings}

</p>

</div>

<div class="section">

<h3>Recommendations</h3>

<p>

${report.recommendations}

</p>

</div>

<div class="section">

<h3>Further Action</h3>

<p>

${report.further_action}

</p>

</div>
<div class="section">

<h3>Suggested Actions</h3>

<ul>

${(report.suggested_actions || [])
  .map(
    (action: string) =>
      `<li style="margin-bottom:8px;">✔ ${action}</li>`
  )
  .join("")}

</ul>

</div>

<div class="section">

<h3>National Cyber Crime Resources</h3>

<table>

<tr>

<td><strong>Portal</strong></td>

<td>https://cybercrime.gov.in</td>

</tr>

<tr>

<td><strong>Helpline</strong></td>

<td>1930</td>

</tr>

<tr>

<td><strong>Email</strong></td>

<td>helpdesk@cybercrime.gov.in</td>

</tr>

</table>

</div>

<div class="section">

<h3>Platform Help Centres</h3>

<table>

<tr>

<td>Instagram</td>

<td>https://help.instagram.com</td>

</tr>

<tr>

<td>Facebook</td>

<td>https://www.facebook.com/help</td>

</tr>

<tr>

<td>X (Twitter)</td>

<td>https://help.x.com</td>

</tr>

<tr>

<td>LinkedIn</td>

<td>https://www.linkedin.com/help</td>

</tr>

<tr>

<td>WhatsApp</td>

<td>https://www.whatsapp.com/contact</td>

</tr>

<tr>

<td>YouTube</td>

<td>https://support.google.com/youtube</td>

</tr>

</table>

</div>

<div class="section">

<h3>Verification</h3>

<table>

<tr>

<td><strong>Verification ID</strong></td>

<td>

SS-${report.id.substring(0,8).toUpperCase()}

</td>

</tr>

<tr>

<td><strong>Generated By</strong></td>

<td>SafeSocial AI Investigation Platform</td>

</tr>

<tr>

<td><strong>Generated On</strong></td>

<td>

${new Date().toLocaleString()}

</td>

</tr>

</table>

</div>

<div class="footer">

Generated by SafeSocial

<br/>

AI-powered Cyber Investigation Platform

</div>

</body>

</html>
`;
// -------------------------------------
// Load HTML into Puppeteer
// -------------------------------------

await page.setContent(html);

await page.waitForNetworkIdle();

// -------------------------------------
// Generate PDF Buffer
// -------------------------------------

const pdfBuffer = await page.pdf({

  format: "A4",

  printBackground: true,

  margin: {

    top: "25px",

    bottom: "25px",

    left: "25px",

    right: "25px",

  },

});

// -------------------------------------
// Close Browser
// -------------------------------------

await browser.close();

// -------------------------------------
// Return PDF
// -------------------------------------

return pdfBuffer;

}